import { DataSource } from 'typeorm';
import {
    MicroActionDefinition,
    MicroActionType,
    EvidenceType,
} from 'src/micro-action-definitions/entities/micro-action-definition.entity';
import { Pac } from 'src/pacs/entities/pac.entity';
import { Rubric } from 'src/evaluation/entities/rubric.entity';

export async function seedMicroActionDefinitions(
    dataSource: DataSource,
    pacs: Pac[],
    rubrics: Rubric[],
) {
    const repo = dataSource.getRepository(MicroActionDefinition);
    const [pac1_1_1, pac1_1_2, pac1_2_1, pac2_1_1, pac2_2_1] = pacs;
    const [rubEntrevistas, rubHipotesis, rubPropuesta, rubMvp] = rubrics;

    const microActions = repo.create([
        // ── PAC_1_1_1 — Identificar problema del usuario ──────────────────────
        {
            pacId: pac1_1_1.id,
            rubricId: rubEntrevistas.id,
            code: 'MA-T1-P1-001',
            instruction: 'Realizá al menos 5 entrevistas de descubrimiento con potenciales usuarios y documentá los hallazgos clave.',
            sortOrder: 1,
            executionWindowDays: 7,
            microActionType: MicroActionType.INTERVIEW,
            isRequired: true,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.FILE,
            consistencyWeight: 0.40,
            collaborationWeight: 0.30,
            sustainabilityWeight: 0.30,
            validFrom: null,
            validTo: null,
        },
        {
            pacId: pac1_1_1.id,
            rubricId: rubEntrevistas.id,
            code: 'MA-T1-P1-002',
            instruction: 'Identificá los 3 patrones de dolor más frecuentes mencionados en las entrevistas.',
            sortOrder: 2,
            executionWindowDays: 3,
            microActionType: MicroActionType.DOCUMENTATION,
            isRequired: true,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.TEXT,
            consistencyWeight: 0.33,
            collaborationWeight: 0.33,
            sustainabilityWeight: 0.34,
            validFrom: null,
            validTo: null,
        },

        // ── PAC_1_1_2 — Validar hipótesis del problema ────────────────────────
        {
            pacId: pac1_1_2.id,
            rubricId: rubHipotesis.id,
            code: 'MA-T1-P2-001',
            instruction: 'Redactá una hipótesis del problema en formato: "Creemos que [segmento] tiene [problema] porque [causa]."',
            sortOrder: 1,
            executionWindowDays: 2,
            microActionType: MicroActionType.RESEARCH,
            isRequired: true,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.TEXT,
            consistencyWeight: 0.50,
            collaborationWeight: 0.25,
            sustainabilityWeight: 0.25,
            validFrom: null,
            validTo: null,
        },
        {
            pacId: pac1_1_2.id,
            rubricId: rubHipotesis.id,
            code: 'MA-T1-P2-002',
            instruction: 'Validá la hipótesis contrastándola con al menos 3 fuentes primarias (entrevistas, observaciones o datos).',
            sortOrder: 2,
            executionWindowDays: 5,
            microActionType: MicroActionType.VALIDATION,
            isRequired: true,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.FILE,
            consistencyWeight: 0.40,
            collaborationWeight: 0.30,
            sustainabilityWeight: 0.30,
            validFrom: null,
            validTo: null,
        },

        // ── PAC_1_2_1 — Definir propuesta de valor ────────────────────────────
        {
            pacId: pac1_2_1.id,
            rubricId: rubPropuesta.id,
            code: 'MA-T1-P3-001',
            instruction: 'Escribí tu propuesta de valor en una sola frase usando la estructura: "Ayudamos a [segmento] a [resultado] mediante [diferencial]."',
            sortOrder: 1,
            executionWindowDays: 2,
            microActionType: MicroActionType.DOCUMENTATION,
            isRequired: true,
            isReusable: true,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.TEXT,
            consistencyWeight: 0.33,
            collaborationWeight: 0.33,
            sustainabilityWeight: 0.34,
            validFrom: null,
            validTo: null,
        },
        {
            pacId: pac1_2_1.id,
            rubricId: rubPropuesta.id,
            code: 'MA-T1-P3-002',
            instruction: 'Compartí la propuesta de valor con 3 usuarios potenciales y registrá su reacción espontánea.',
            sortOrder: 2,
            executionWindowDays: 4,
            microActionType: MicroActionType.VALIDATION,
            isRequired: false,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.TEXT,
            consistencyWeight: 0.30,
            collaborationWeight: 0.40,
            sustainabilityWeight: 0.30,
            validFrom: null,
            validTo: null,
        },

        // ── PAC_2_1_1 — Diseñar arquitectura MVP ──────────────────────────────
        {
            pacId: pac2_1_1.id,
            rubricId: rubMvp.id,
            code: 'MA-T2-P1-001',
            instruction: 'Diseñá un diagrama de arquitectura del MVP indicando las capas principales, tecnologías elegidas y flujo de datos.',
            sortOrder: 1,
            executionWindowDays: 7,
            microActionType: MicroActionType.PROTOTYPE,
            isRequired: true,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.IMAGE,
            consistencyWeight: 0.40,
            collaborationWeight: 0.20,
            sustainabilityWeight: 0.40,
            validFrom: null,
            validTo: null,
        },
        {
            pacId: pac2_1_1.id,
            rubricId: rubMvp.id,
            code: 'MA-T2-P1-002',
            instruction: 'Documentá las decisiones técnicas clave y sus justificaciones en un documento de arquitectura.',
            sortOrder: 2,
            executionWindowDays: 3,
            microActionType: MicroActionType.DOCUMENTATION,
            isRequired: true,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.FILE,
            consistencyWeight: 0.33,
            collaborationWeight: 0.33,
            sustainabilityWeight: 0.34,
            validFrom: null,
            validTo: null,
        },
        {
            pacId: pac2_1_1.id,
            rubricId: rubMvp.id,
            code: 'MA-T2-P1-003',
            instruction: 'Validá la arquitectura propuesta con un mentor técnico o par experto y registrá el feedback recibido.',
            sortOrder: 3,
            executionWindowDays: 4,
            microActionType: MicroActionType.VALIDATION,
            isRequired: false,
            isReusable: false,
            evidenceRequired: true,
            expectedEvidenceType: EvidenceType.LINK,
            consistencyWeight: 0.25,
            collaborationWeight: 0.50,
            sustainabilityWeight: 0.25,
            validFrom: null,
            validTo: null,
        },

        // ── PAC_2_2_1 — Testear escalabilidad (categoría inactiva) ────────────
        {
            pacId: pac2_2_1.id,
            rubricId: null,
            code: 'MA-T2-P2-001',
            instruction: 'Definí los criterios mínimos de escalabilidad esperados para el primer año de operación.',
            sortOrder: 1,
            executionWindowDays: 3,
            microActionType: MicroActionType.OTHER,
            isRequired: false,
            isReusable: false,
            evidenceRequired: false,
            expectedEvidenceType: null,
            consistencyWeight: null,
            collaborationWeight: null,
            sustainabilityWeight: null,
            validFrom: null,
            validTo: null,
        },
    ] as unknown as MicroActionDefinition[]);

    const saved = await repo.save(microActions);
    console.log('✅ MicroActionDefinitions creadas:', saved.length);
    return saved;
}